apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mp-indicator-mongo-persistent-volume-claim
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
