# Application Properties
Application.Port:
  value: 8080

# MongoDB Properties
MongoDB.URI:
#  value: mongodb://localhost:27017
#  value: mongodb://${DB_MONGO_USER}:${DB_MONGO_PASSWORD}@${DB_MONGO_HOST}:${DB_MONGO_PORT}
  value: mongodb://admin:admin@localhost:27017
MongoDB.DatabaseName:
  value: mp-indicator

# Kafka Properties
Kafka.bootstrap.servers:
  value: localhost:9092
Kafka.group.id:
  value: mp-indicator
Kafka.auto.offset.reset:
  value: earliest

# RabbitMQ Properties
RabbitMQ.URI:
  value: amqp://dev_mktplace:riS9udae@localhost:5672/dev01_mktplace

# Rest Integration Properties
Integration.mp-order-search.url:
  value: https://mock.com/mp-order-search

# Cache Properties
Redis.hosts:
  value: localhost:6379

# Tracing Properties
Tracing.server.name:
  value: mp-indicator-go
Tracing.service.name.key:
  value: mp-indicator-go
Tracing.server.url:
  value: http://localhost:9411/api/v2/spans